"""knowledge graph tables

Revision ID: 17e623d408df
Revises: 30d783a96ae4
Create Date: 2026-07-27 16:24:35.402750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17e623d408df'
down_revision: Union[str, Sequence[str], None] = '30d783a96ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('node_type', sa.Enum('guideline', 'article', 'recommendation', 'term', name='knowledge_node_type'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('pubmed', 'nice', name='knowledge_source_type'), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'superseded', 'withdrawn', 'draft', name='knowledge_status'), nullable=False),
    sa.Column('authority_tier', sa.SmallInteger(), nullable=True),
    sa.Column('category', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('update_cadence', sa.Enum('static', 'periodic', 'live', name='knowledge_update_cadence'), nullable=False),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_nodes_effective_date', 'knowledge_nodes', ['effective_date'], unique=False)
    op.create_index('ix_knowledge_nodes_external_ref', 'knowledge_nodes', ['external_ref'], unique=False)
    op.create_index('ix_knowledge_nodes_status_source', 'knowledge_nodes', ['status', 'source_type'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('from_node_id', sa.Uuid(), nullable=False),
    sa.Column('to_node_id', sa.Uuid(), nullable=False),
    sa.Column('edge_type', sa.Enum('SUPERSEDES', 'DEFINED_BY', 'EXCEPTION_TO', 'CITES', 'RELATED_TO', name='knowledge_edge_type'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_by', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_node_id', 'to_node_id', 'edge_type', name='uq_knowledge_edge')
    )
    op.create_index(op.f('ix_knowledge_edges_edge_type'), 'knowledge_edges', ['edge_type'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_from_node_id'), 'knowledge_edges', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_to_node_id'), 'knowledge_edges', ['to_node_id'], unique=False)
    op.add_column('embeddings', sa.Column('node_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_embeddings_node_id'), 'embeddings', ['node_id'], unique=False)
    op.create_foreign_key('fk_embeddings_node_id', 'embeddings', 'knowledge_nodes', ['node_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Explicitly drop the PostgreSQL ENUM types after the tables (see
    7a5287c24302_dataset_versioning_tables.py) — ``create_table`` creates them
    implicitly on upgrade but Alembic never drops them on downgrade, which would
    orphan the types and break a subsequent ``upgrade head``.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_embeddings_node_id', 'embeddings', type_='foreignkey')
    op.drop_index(op.f('ix_embeddings_node_id'), table_name='embeddings')
    op.drop_column('embeddings', 'node_id')
    op.drop_index(op.f('ix_knowledge_edges_to_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_from_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_edge_type'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index('ix_knowledge_nodes_status_source', table_name='knowledge_nodes')
    op.drop_index('ix_knowledge_nodes_external_ref', table_name='knowledge_nodes')
    op.drop_index('ix_knowledge_nodes_effective_date', table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###
    sa.Enum(name='knowledge_edge_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='knowledge_update_cadence').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='knowledge_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='knowledge_source_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='knowledge_node_type').drop(op.get_bind(), checkfirst=True)
